### ISSUE TITLE
Wamv sinks in Rviz despite valid GPS and IMU data

### ISSUE THREAD

**Issue by ayarst** [osrf/vrx#376] opened 2021-10-07 15:49 UTC
No matter what I do, when I open up Rviz, my wamv slowly descends deeper and deeper into the ocean. The localization example does not help nor does implementing our own Kalman filter. After checking the sensor data, we found that the GPS is reporting an altitude of approximately 1.2m and the IMU is reporting a linear acceleration in the z of approximately 9.8m/s2, both of which make sense. The only area of concern is the fact that both sensors report a covariance of 0.0 across the board (even after adding Gaussian noise to both sensors). Below is a screenshot of our wamv and its LiDAR scans way below the ground plane. We are not sure if this is a bug or something that we are doing wrong. Any help will be appreciated!

![Screenshot from 2021-10-07 11-44-52](https://user-images.githubusercontent.com/79225975/136419444-a9d46bf2-853d-4a8e-9979-bda41385d1e1.png)

**Comment by caguero** [comment] 2021-11-08 16:39
I'm closing this issue as I'm unable to reproduce it but feel free to reopen if still persists providing extra information.

**Closed by caguero** 2021-11-08 16:39 UTC

**Comment by ayarst** [comment] 2021-11-16 17:14
@caguero, I think it was an issue with my navsat transform but it's fixed now.

**Comment by caguero** [comment] 2021-11-16 17:39
> @caguero, I think it was an issue with my navsat transform but it's fixed now.

Good to know :)
