### ISSUE TITLE
Xacro files failing during catkin_make

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#196] opened 2020-03-04 21:21 UTC
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/196)) by Anonymous.**

----------------------------------------
Hello,

I am trying to compile your source code outside of the docker image. I have an installation of Gazebo9 and ROS melodic, along with all the dependencies I could see in the docker. I keep seeing the following issues when I try to run `catkin_make`. It appears many times for varying `xacro` files.
```
#!bash
-- xacro: determining deps for: urdf/wamv_gazebo.urdf.xacro ...
CMake Warning at xacro/cmake/xacro-extras.cmake:87 (message):
  failed to determine deps for: urdf/wamv_gazebo.urdf.xacro

  error: substitution args not supported: No module named msg

  when processing file: urdf/wamv_gazebo.urdf.xacro

Call Stack (most recent call first):
  xacro/cmake/xacro-extras.cmake:187 (xacro_add_xacro_file)
  vrx/wamv_gazebo/CMakeLists.txt:13 (xacro_add_files)
``` 
This has happened alternatively for `msg`, `Log`, and others, depending on which dependencies I set in `package.xml`, so I think it may be a dependency issue, if you'd help clarify. I don't think I should need to alter your `package.xml` files..? 

There is also this warning (though I don't think it has any effect):
```
#!bash
CMake Warning (dev) at /usr/share/cmake-3.10/Modules/FindBoost.cmake:911 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /usr/share/OGRE/cmake/modules/FindOGRE.cmake:318 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:175 (find_package)
  vrx/vrx_gazebo/CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```
And this: 
```
#!bash
CMake Warning (dev) in vrx/vrx_gazebo/msgs/CMakeLists.txt:
  Policy CMP0071 is not set: Let AUTOMOC and AUTOUIC process GENERATED files.
  Run "cmake --help-policy CMP0071" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  For compatibility, CMake is excluding the GENERATED source file(s):

    "/home/CYBERNET/ewills/gazebo_sims/tautog3/build/vrx/vrx_gazebo/msgs/light_buoy_colors.pb.cc"
    "/home/CYBERNET/ewills/gazebo_sims/tautog3/build/vrx/vrx_gazebo/msgs/dock_placard.pb.cc"
    "/home/CYBERNET/ewills/gazebo_sims/tautog3/build/vrx/vrx_gazebo/msgs/header.pb.cc"
    "/home/CYBERNET/ewills/gazebo_sims/tautog3/build/vrx/vrx_gazebo/msgs/time.pb.cc"

  from processing by AUTOMOC and AUTOUIC.  If any of the files should be
  processed, set CMP0071 to NEW.  If any of the files should not be
  processed, explicitly exclude them by setting the source file property
  SKIP_AUTOGEN:

    set_property(SOURCE file.h PROPERTY SKIP_AUTOGEN ON)

This warning is for project developers.  Use -Wno-dev to suppress it.
```
Along with this target fail:
```
#!bash
CMake Warning (dev) at vrx/vrx_gazebo/CMakeLists.txt:118 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "vrx_gazebo_generate_services_cpp" of target
  "scoring_plugin" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it
```

Which eventually gives:
```
#!bash
[  1%] Built target wamv_description__xacro_auto_generate_to_devel_space_
vrx/wamv_gazebo/CMakeFiles/wamv_gazebo__xacro_auto_generate_to_devel_space_.dir/build.make:73: *** unterminated variable reference.  Stop.
CMakeFiles/Makefile2:122481: recipe for target 'vrx/wamv_gazebo/CMakeFiles/wamv_gazebo__xacro_auto_generate_to_devel_space_.dir/all' failed
make[1]: *** [vrx/wamv_gazebo/CMakeFiles/wamv_gazebo__xacro_auto_generate_to_devel_space_.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
Could you help clarify what might be going on?
Thank you!

**Comment by caguero** [comment] 2020-06-02 14:36
I can't reproduce this issue either. Please, let us know if you're using the right Gazebo version or if going through the referenced tutorial helped. I'll close the issue but feel free to reopen if you have further information.

**Closed by caguero** 2020-06-02 14:36 UTC
Labels: bug, major
