### ISSUE TITLE
Inconsistent visual placard symbols.

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx#163] opened 2019-09-19 18:10 UTC
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/issues/163)) by Brian Bingham (Bitbucket: [brian_bingham](https://bitbucket.org/%7B9cdea257-248f-486e-8858-49d8485a916f%7D/)).**

----------------------------------------
Running the 2018 dock example: `roslaunch vrx_gazebo dock.launch verbose:=true`

The `vrx_gazebo/worlds/dock.world.xacro` specifies red\_circle for bay1 and red\_cross for bay2, but the dock shows up with blue\_circle on both placards.

* The world uses the static dock\_2018 model. Changing the <color> and <shape> tags in the model.sdf.erb file can set the initial symbol values.
* The shuffling functionality seems to work `rostopic pub /vrx/dock_2018_placard1/shuffle std_msgs/Empty "{}"`
* Tried going back to [this commit](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx/commits/a29694cd3be48c771e59fbc5c30b9db8bd2a2e12) (d1838a988ccb791e7dcf2c0fef1adf237e0e31d1) before reflections/refractions and recent dock tweaks, same behavior.
* In the dock\_2018/model.sdf.erb file, I set the PlacardPlugin <shuffle> tag to false.    Same behavior.

My understanding was that the ScanDockScoringPlugin::DockChecker objects should publish to the PlacardPlugin objects via Gazebo transport to be able to set the symbol \(color\+shape\) to be consistent with the <symbol> tags in the <bay> elements - true?

‌

**Comment by M1chaelM** [comment] 2022-06-09 18:19
I can no longer reproduce this behavior. Running the example shows blue circles until the plugin instantiates, at which point they change to red circle and red cross. It may be that the problem was caused by the timing of publication of the placard symbols, as documented in issue #451 and resolved in PR #452. In any case, I think we can close this.

**Closed by M1chaelM** 2022-06-09 18:19 UTC
Labels: bug, major, Plugin
